### ISSUE TITLE
意见与建议

### ISSUE THREAD

**Issue by ELE-Clouds** [ianhom/LittleRedFlower#1]
1. 需要增加童锁功能，防止小孩调皮和误触发，形成无效数据；
2. 可增加语音功能，播放设定语音；
3. 可改用LED点阵屏或其它更清晰的屏，使图案更加清晰、形象；
4. 可以改小红花增加计数的方法由按钮改为由一块铁质小红花经上磁后磁化（软磁）后投入收集盒（瓶）中，瓶口处触发干簧管进行计数，再经过消磁通道消磁后落入瓶中，只有经过上磁的小红花才有计数功能；
5. 可以增加其它颜色的花代表不同的分值，区分奖励等级，形成积分，年底可任积分兑换压岁钱的额外奖金或奖品。

**Comment by ianhom** [comment]
不错的建议，后面会认真考虑，欢迎参与
